### ISSUE TITLE
Client Secret is Explicitly Defined in index.js

### ISSUE THREAD

**Issue by WholeRoastedDuck** [ThunderBotDevelopment/ThunderBot#7]
On line 178 in /src/index.js:

```js
 if (urlObj.query.code) {
    const accessCode = urlObj.query.code;
    const data = {
             client_id: '783743297453686795',
    	     client_secret: 'G3eTz_qfuW7fvicuBPnON7kRbJCekGn1',
    	     grant_type: 'authorization_code',
    	     redirect_uri: 'https://thundebot.yodacode.repl.co/authorized',
    	     code: accessCode,
    	     scope: 'identify guilds email',
    };
```
The client secret should be moved to an environment variable or a command line argument as it is supposed to be "secret". Also, the client id probably should be too in case anyone else wants to host it without making some changes.

**Comment by YodaLightsabr** [comment]
> On line 178 in /src/index.js:
> 
> ```js
>  if (urlObj.query.code) {
>     const accessCode = urlObj.query.code;
>     const data = {
>              client_id: '783743297453686795',
>     	     client_secret: 'G3eTz_qfuW7fvicuBPnON7kRbJCekGn1',
>     	     grant_type: 'authorization_code',
>     	     redirect_uri: 'https://thundebot.yodacode.repl.co/authorized',
>     	     code: accessCode,
>     	     scope: 'identify guilds email',
>     };
> ```
> 
> The client secret should be moved to an environment variable or a command line argument as it is supposed to be "secret". Also, the client id probably should be too in case anyone else wants to host it without making some changes.

Lol. Time to regenerate the client secret. Do you have a PR ready?

**Comment by WholeRoastedDuck** [comment]
No
